# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).




User.destroy_all
Cart.destroy_all
Product.destroy_all
AddProduct.destroy_all
Review.destroy_all
Category.destroy_all

User.reset_pk_sequence
Cart.reset_pk_sequence
Product.reset_pk_sequence
AddProduct.reset_pk_sequence
Review.reset_pk_sequence
Category.reset_pk_sequence

###################### CATEGORIES #################################################

gowns = Category.create(name: "Gowns")
masks = Category.create(name: "Masks")
gloves = Category.create(name: "Gloves")
sanitizers = Category.create(name: "Hand Sanitizers")
wipes = Category.create(name: "Wipes")
pets = Category.create(name: "Pets")

######################## PRODUCTS ###################################################

gown1 = Product.create(name: "Unisex Barrier Gown", price: 25, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://cdns.webareacontrol.com/prodimages/1000-X-1000/1/s/18120183614Medline-Unisex-Blockade-Antistatic-Barrier-Backless-Gowns-L.png", category_id: gowns.id)
gown2 = Product.create(name: "Isolation Gown", price: 10, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",  image: "https://image.rehabmart.com/include-mt/img-resize.asp?path=/imagesfromrd/isolation_gowns_level_2.jpg", category_id: gowns.id)
gown3 = Product.create(name: "Disposable Isolation Gowns - Knit Cuffs", price: 15, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://cdn.shopify.com/s/files/1/0251/8623/8541/products/isolation-gown-web_500x.jpg", category_id: gowns.id)


mask1 = Product.create(name: "Go Vote! Mask", price: 8, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/16160482/r/il/d58135/2544752107/il_794xN.2544752107_blpv.jpg" , category_id: masks.id)
mask2 = Product.create(name: "Black Lives Matter Mask", price: 8, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/23838642/r/il/981e33/2426065535/il_1588xN.2426065535_34l6.jpg" , category_id: masks.id)
mask3 = Product.create(name: "Dog Mom Fabric Mask", price: 8, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/22910236/r/il/1e7718/2429310812/il_1588xN.2429310812_fogo.jpg" , category_id: masks.id)
mask4 = Product.create(name: "Natural Linen Face Mask", price: 12, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/23149672/r/il/9ab315/2348475297/il_1588xN.2348475297_noz8.jpg" , category_id: masks.id)
mask5 = Product.create(name: "Tie Dye Face Mask", price: 10, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/23007997/r/il/29f83a/2513809922/il_794xN.2513809922_ieul.jpg" , category_id: masks.id)
mask6 = Product.create(name: "Organic Cotton Mask - Blush Pink (Pack of 4)", price: 30, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/23466013/r/il/2f8673/2343340900/il_1588xN.2343340900_d13i.jpg" , category_id: masks.id)
mask7 = Product.create(name: "Organic Cotton Mask - Blue (Pack of 4)", price: 30, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/23466013/r/il/9601f3/2503447718/il_794xN.2503447718_8yfu.jpg" , category_id: masks.id)
mask8 = Product.create(name: "Reusable Washable Cotton face mask with prints", price: 40, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/23322164/r/il/fdea85/2568540529/il_1588xN.2568540529_qvt8.jpg" , category_id: masks.id)
mask9 = Product.create(name: "Pokemon Mask with Pikachu Print", price: 17, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/19472564/r/il/61c685/2507783468/il_1588xN.2507783468_be1y.jpg" , category_id: masks.id)
mask10 = Product.create(name: "Neutral Cream Beige Face Masks (Set of 2)", price: 20, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://i.etsystatic.com/23014560/r/il/e570a3/2481879785/il_794xN.2481879785_dsdd.jpg" , category_id: masks.id)

glove1 = Product.create(name: "Powderfree Blue Nitrile Gloves (Pack of 200)", price: 50, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://www.secaretrade.com/product_images/Medium/Blue%20Nitrile%20Gloves%20-%20Powder%20Free.jpg" , category_id: gloves.id)
glove2 = Product.create(name: "Powderfree White Nitrile Gloves (Pack of 200)", price: 45, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://www.envirosafetyproducts.com/media/product/b06/white-nitrile-exam-gloves-721.jpg" , category_id: gloves.id)
glove3 = Product.create(name: "Powderfree Vinyl Gloves (Pack of 100)", price: 30, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://www.secaretrade.com/product_images/Medium/A09-0421.jpg" , category_id: gloves.id)

sani1 = Product.create(name: "Hand Sanitizer", price: 7, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://cdn.shopify.com/s/files/1/2974/6610/products/public-goods-hand-sanitizer-859982_1024x1024@2x.jpg" , category_id: sanitizers.id)
sani2 = Product.create(name: "Grapefruit Hydrating Hand Sanitizer", price: 8, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://cdn.shopify.com/s/files/1/2974/6610/products/curie-grapefruit-hydrating-hand-sanitizer-131585_1024x1024@2x.png" , category_id: sanitizers.id)
sani3 = Product.create(name: "Orange Neroli Hydrating Hand Sanitizer", price: 8, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://cdn.shopify.com/s/files/1/2974/6610/products/curie-orange-neroli-hydrating-hand-sanitizer-825291_1024x1024@2x.png" , category_id: sanitizers.id)
sani4 = Product.create(name: "White Tea Hydrating Hand Sanitizer", price: 8, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://cdn.shopify.com/s/files/1/2974/6610/products/curie-white-tea-hydrating-hand-sanitizer-235491_1024x1024@2x.png" , category_id: sanitizers.id)
sani5 = Product.create(name: "Hand Sanitizer Spray", price: 10, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://cdn.shopify.com/s/files/1/2974/6610/products/public-goods-hand-sanitizer-spray-211201_1024x1024@2x.jpg" , category_id: sanitizers.id)

wipe1 = Product.create(name: "Care Touch Alcohol-Free Hand Sanitizing Wipes", price: 24, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://images-na.ssl-images-amazon.com/images/I/81bowURn0ZL._SX679_.jpg" , category_id: wipes.id)
wipe2 = Product.create(name: "Alta + Antibacterial Hand Wipes", price: 18, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://images-na.ssl-images-amazon.com/images/I/61n6A17Xg9L._AC_SL1280_.jpg" , category_id: wipes.id)
wipe3 = Product.create(name: "Personal Care Protection Wipes for Hands", price: 20, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://images-na.ssl-images-amazon.com/images/I/81PMqDw7iJL._AC_SX679_.jpg" , category_id: wipes.id)

pet1 = Product.create(name: "Please Wash Your Paws Dog Bandana", price: 11, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://images-na.ssl-images-amazon.com/images/I/71PK3amiAeL._AC_SL1500_.jpg" , category_id: pets.id)
pet2 = Product.create(name: "Spread Love Not Germs Dog Bandana", price: 11, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://images-na.ssl-images-amazon.com/images/I/71r5U8zEqRL._AC_SL1500_.jpg" , category_id: pets.id)
pet3 = Product.create(name: "Do Not Pet Dog Bandana", price: 11, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", image: "https://images-na.ssl-images-amazon.com/images/I/71H-lmCLTjL._AC_SL1500_.jpg" , category_id: pets.id)


######################## CART ###################################################

# cart_1 = Cart.create(user_id: user_1.id, history: false)
# cart_2 = Cart.create(user_id: user_2.id, history: false)

######################## addProducts ##############################################

# addP_1 = AddProduct.create(cart_id: cart_1.id, product_id: product_1.id, quantity: 3)
# addP_2 = AddProduct.create(cart_id: cart_2.id, product_id: product_2.id, quantity: 2)


######################## USERS ###################################################

user_1 = User.create(name: 'Anna', username: 'demo1', street_address: "Main st", street_address_2: "Apt 4M", city: "Queens", zip_code: 12345)
user_2 = User.create(name: 'Franklin', username: 'demo2', street_address: "Lonely Rd.", street_address_2: "Apt Z", city: "Flushing", zip_code: 11345)


######################## REVIEWS #################################################

rev_1 = Review.create(user_id: user_1.id, product_id: pet1.id, content: "Great gloves", nickname: "Banana", star_rating: 4)
rev_2 = Review.create(user_id: user_1.id, product_id: mask1.id, content: "sucks ", nickname: "Banana", star_rating: 4)
rev_3 = Review.create(user_id: user_2.id, product_id: pet1.id, content: "so so", nickname: "appple", star_rating: 2)
rev_4 = Review.create(user_id: user_2.id, product_id: mask1.id, content: "I wanted them on black", nickname: "apple", star_rating: 5)








